queue_rules:
  - name: main
    conditions:
      - base~=^Agoric


pull_request_rules:
  - name: automerge to Agoric* with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>0"
      - base~=^Agoric
      - label=automerge
    actions:
      queue:
        name: main
        method: merge
      # commit_message: title+body
  - name: backport patches to Agoric branch
    conditions:
      - base=Agoric-ag0
      - label=backport/Agoric
    actions:
      backport:
        branches:
          - Agoric
  - name: backport patches to Agoric-ag0 branch
    conditions:
      - base=Agoric
      - label=backport/Agoric-ag0
    actions:
      backport:
        branches:
          - Agoric-ag0
